### ISSUE TITLE
Disable window animation?

### ISSUE THREAD

**Issue by Kieaer** [pypy-vrc/VRCX#453]
I want very fast responsiveness but window transition animations prevent quick manipulation.

**Comment by Natsumi-sama** [comment]
`%AppData%\VRCX\custom.css`
```css
.dialog-fade-enter-active,
.dialog-fade-leave-active,
.msgbox-fade-enter-active,
.msgbox-fade-leave-active,
.el-zoom-in-center-enter-active,
.el-zoom-in-center-leave-active,
.el-zoom-in-top-enter-active,
.el-zoom-in-top-leave-active,
.el-zoom-in-bottom-enter-active,
.el-zoom-in-bottom-leave-active,
.el-zoom-in-left-enter-active,
.el-zoom-in-left-leave-active,
.el-zoom-in-right-enter-active,
.el-zoom-in-right-leave-active {
  animation: unset !important;
  transition: none !important;
}
```
